### ISSUE TITLE
Need help with the setup

### ISSUE THREAD

**Issue by thebugsyy** [Ad882/Smart-CO-monitoring#1]
hello, I was trying to setup this project on my machine but from long I am stuck with coapthon. I'd be very nice of you if you could help me with this. I looked up into your profile for other ways of contact, but couldn't find any.

![image](https://github.com/Ad882/Smart-CO-monitoring/assets/143344387/dfc7d5ff-40f7-4dcb-84c8-c5a836271f31)

and getting this error repeatedly even after pip installing coapthon:

```
Traceback (most recent call last):
  File "coap_actuator.py", line 5, in <module>
    from coapthon.client.helperclient import HelperClient
ImportError: No module named coapthon.client.helperclient
```

**Comment by Ad882** [comment]
Hello my friend,

Sorry i am not an expert I only did (depending on the python version):
sudo pip (or pip3) install copathon (or coapthon3)

That's all.
If you keep struggling, I advice you to check these links:
https://github.com/Tanganelli/CoAPthon
https://github.com/Tanganelli/CoAPthon3

The authors are really more qualified than me. But I appreciate your request and hope you will find a solution!

**Comment by thebugsyy** [comment]
sure, I will check the mentioned resources : )...thanks

**Comment by thebugsyy** [comment]
got a new error :)
tried web searching the error but couldn't find the solution.
See if you can help. I am too much of a beginner with cooja
![image](https://github.com/Ad882/Smart-CO-monitoring/assets/143344387/752df001-a97d-48eb-a0eb-40fb99169d06)

**Comment by thebugsyy** [comment]
hello!!!
can you please provide all the commands in the series you ran after the setting up the border route, there may be a possibility that i'd have missed something :(

**Comment by rajtiwariee** [comment]
Bonjour Adrien , je suis confronté au problème avec MQTT.......pouvez-vous s'il vous plaît mentionner toutes les commandes après la configuration du routeur frontalier....

**Comment by Ad882** [comment]
Hello,

You have to install _mosquitto_, have you done it ? (https://mosquitto.org/download/)

Once it is done you have to start the broker:
`sudo systemctl enable mosquitto.service`

Then, I advise you have to check if the broker started properly: 
`sudo service mosquitto status`

(You should see that the broker is active).

To see if it works, open 2 windows on your terminal. 
On the first one you will subscribe to the topic hello:
`mosquitto_sub -d -t hello`

On the other one you will publish a message on the topic: 
`mosquitto_pub -d -t hello -m "Hello world!"`

If you see the message arriving on the first window, it means it works!

Then if everything works, you can retry to launch the cooja simulation.
/!\ Be careful, sometimes the broker gets disconnected, you just have to launch the simulation again /!\

I hope it helped you.

**Comment by thebugsyy** [comment]
first of all thanks for the response adrien!!!

the steps you mentioned works fine, but still the the broker was getting disconnected.

then i tried replacing the broker ip address to 127.0.01 and as a result now  mqtt is not getting disconnected from the broker but it is neither publishing or subscribing to anything.

this is my first introduction to cooja and mqtt and i really think i am missing out on something really silly step.



![image](https://github.com/Ad882/Smart-CO-monitoring/assets/143344387/d587517e-17ba-41b4-a3cc-d0c26789f7a1)

**Comment by Ad882** [comment]
Hello,

I tried to look at all the steps and I do not know where I am missing something.

I am sorry, I am not a cooja expert either, I installed the packages only once a few month ago.

Sorry

**Comment by thebugsyy** [comment]
no worries Adrien!!!
I have almost set it up. The problem was with the **mqtt_collector.py** due the loop_forever() the client3 and client4 were not executing. I applied threading there and its working now though it prints same values thrice😂...but no worries i"ll resolve it too somehow :)
![image](https://github.com/Ad882/Smart-CO-monitoring/assets/143344387/23160af4-7644-420b-894e-7b4c6d723d9c)

Thanks for the all the help!!!!
